import Header from '@/component/Header'
import './globals.css'

export const metadata = {
  title: 'Hello world',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  )
}
