import Header from '@/component/Header'
import './globals.css'
import Providers from './Providers'

export const metadata = {
  title: 'Hello world',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Providers>
          <Header/>
          {children}
        </Providers>
        
      </body>
    </html>
  )
}
